$lines = Get-Content coverage\lcov.info;
 $results = @();
 $currentFile = "";
 $hit = 0;
 $total = 0;
 foreach ($line in $lines) { if ($line -match "^SF:(.+)") { if ($currentFile -ne "") { $pct = if ($total -gt 0) { [math]::Round(100 * $hit / $total, 1) } else { 0 };
 $results += [PSCustomObject]@{File=$currentFile -replace ".*/VulkanEngine/", "";
 Pct=$pct;
 Hit=$hit;
 Total=$total} };
 $currentFile = $matches[1];
 $hit = 0;
 $total = 0 } elseif ($line -match "^DA:(\d+),(\d+)") { $total++;
 if ([int]$matches[2] -gt 0) { $hit++ } } };
 if ($currentFile -ne "") { $pct = if ($total -gt 0) { [math]::Round(100 * $hit / $total, 1) } else { 0 };
 $results += [PSCustomObject]@{File=$currentFile -replace ".*/VulkanEngine/", "";
 Pct=$pct;
 Hit=$hit;
 Total=$total} };
 $results | Sort-Object Pct | Format-Table @{L="Coverage";
E={"{0,5:N1}%" -f $_.Pct}}, Hit, Total, File -AutoSize